{
 "title": "Load Average Nodos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Nodo", "label": "Nodo", "query": { "query": "kube_node_labels" } }
  ]
 },
 "panels": [
  { "title": "CPU Nodos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average 1 min",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$Nodo\"}",
     "legendFormat": "{{instance}}"
    },
    { "expr": "4", "legendFormat": "Max CPU" }
   ]
  },
  {
   "title": "Uso de CPU por container en nodo seleccionado",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$Nodo\", pod!=\"\", container!=\"POD\", container!=\"\"}[1m])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Memoria Nodos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memoria en uso.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " 100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"$Nodo\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\"$Nodo\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"$Nodo\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$Nodo\"}[5m])))\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top containers en uso de memoria en Mb.",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10 , (sum by(container,namespace) (container_memory_working_set_bytes{container!=\"pod\",image!=\"\",node=~\"$Nodo\"})/1048576) )",
     "legendFormat": "Container=[{{container}}]  Namespace=[{{namespace}}]"
    }
   ]
  }
 ]
}