{
 "title": "K8/Openshift Projects and Pods",
 "description": "Displays Namespace utilization",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods CPU usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Project $Namespace Quotas - CPU Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (limit)"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total Pods memory usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 17, "w": 22, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes", "label": "Memory " }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Project $Namespace Quotas - Memory Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace  }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace }} (limit)"
    }
   ]
  }
 ]
}