apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: observabilidad
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    # auth.ldap:
    #   config_file: /etc/grafana-configmaps/ldap-config/ldap.toml
    #   enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  # configMaps:
  #   - ldap-config
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  dataStorage:
    accessModes:
      - ReadWriteOnce
    class: gp2
    size: 1Gi
  ingress:
    enabled: true