apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-app
  namespace: observabilidad
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: 'http://prometheus-operated.observabilidad.svc:9090'
      version: 1
    # - basicAuthUser: access
    - access: proxy
      editable: true
      name: K8s
      url: 'https://prometheus-k8s.openshift-monitoring.svc:9091'
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer <TOKEN>"
      version: 1
      type: prometheus
  name: example-datasources.yaml
